feature/blog-searching
seuungkei/meerkats pull request #18
Opened 2023-05-06 14:47 UTC by Hwi227

2023-05-06 14:53 UTC, seuungkei requested changes

2023-05-06 14:53 UTC, seuungkei commented on src/services/searchService.ts
> +    return this.Repository.blogSearch(postTitle);
await 처리를 해주세요!

2023-05-06 15:02 UTC, seuungkei requested changes

2023-05-06 15:02 UTC, seuungkei commented on src/routes/searchRouter.ts
> +router.post('/blog', getSearchDataController.blogSearch);
검색 기능 같은경우에는 GET 메서드가 적합하지 않을까요?

2023-05-06 15:02 UTC, seuungkei commented on src/controllers/searchController.ts
> +    return res.status(201).json({ data: getBlogSearchData });
200 상태코드가 적합해 보입니다!

2023-05-08 06:50 UTC, Hwi227 commented on src/routes/searchRouter.ts
> +router.post('/blog', getSearchDataController.blogSearch);
수정완료

2023-05-08 06:50 UTC, Hwi227 commented on src/controllers/searchController.ts
> +    return res.status(201).json({ data: getBlogSearchData });
수정완료

2023-05-08 06:55 UTC, merged