[ADD] Feature/movie detail
seuungkei/meerkats pull request #9
Opened 2023-04-25 08:55 UTC by seuungkei

2023-05-04 11:51 UTC, Hwi227 requested changes

2023-05-04 11:51 UTC, Hwi227 commented on src/controllers/movieController.ts
> +    const { content, commentId } = req.body;
commentId는 req.params로 받을 수 있게 수정해주세요.

2023-05-04 11:51 UTC, Hwi227 commented on src/controllers/movieController.ts
> +  movieLike = catchAsync(async (req: Request & IReqUser, res: Response) => {
영화 좋아요를 생성 삭제하는 로직인가요? 아니면 좋아요를 카운트하는 로직인가요? movieRepository.ts까지 봐야 파악이 가능하네요.
변수명을 좀더 명확하게 해주세요.

2023-05-04 11:51 UTC, Hwi227 commented on src/controllers/movieController.ts
> +
skip과 take 값이 없을 경우의 예외처리도 필요해 보입니다.

2023-05-04 11:51 UTC, Hwi227 commented on src/services/movieService.ts
> +    const playlistVideoTitle = await this.Youtube.getMovieTrailerPlaylist(movieTrailerDetailData.name);
```suggestion
    const [mainVideo, playlistVideoTitle] = await Promise.all([
      this.Youtube.getMovieTrailerVideoId(movieTrailerDetailData.name),
      this.Youtube.getMovieTrailerPlaylist(movieTrailerDetailData.name)
    ]);
```
이렇게 병렬처리 하는방법은 어떨까요?
테스트 해보고 문제가 없다면 제 생각에는 이게 더 좋아보입니다.

2023-05-05 11:35 UTC, seuungkei commented on src/controllers/movieController.ts
> +    const { content, commentId } = req.body;
수정완료!

2023-05-05 11:35 UTC, seuungkei commented on src/controllers/movieController.ts
> +  movieLike = catchAsync(async (req: Request & IReqUser, res: Response) => {
수정완료!

2023-05-05 11:43 UTC, seuungkei commented on src/services/movieService.ts
> +    const playlistVideoTitle = await this.Youtube.getMovieTrailerPlaylist(movieTrailerDetailData.name);
수정 온료!

2023-05-05 11:43 UTC, seuungkei commented on src/controllers/movieController.ts
> +
수정완료

2023-05-06 14:19 UTC, merged